language: java
jdk: openjdk8
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version | grep -v '\[')
deploy:
  provider: releases
  api_key:
    secure: TaWXrg5y0wS2WBguaI9x8a/Wk0l6wKsAYfcsrUM+uly6Eh60p2n3EH2/n+fZAmKJFpg9t745H2yFJHVKIVuKQY1khPhaxx8apcnsWnP0CQSpFC6zc7ciSgE8mT2whY4EsFX7izHYzcbHF3iuZ3DuKY/wxp+ToYL8oMS7jwZhaxrGl1857J9JW9dFogmGvOsq4aYY0lezSCjxB/ZuHuISXTo2xZww/0iFr1pXWrL0seG9T7jeXv2tJK1V2oQaho7dpSrB8kH6qiBibSH4ieKu9vLugr4UaP3ej7ldPWEozbi63TAR8bf9BHRHcmlcasvyDugGgIi8qkCBg7oVtaCpmafCNgdscttZLED2jt34gsWGwx614vNf4Xgusbb6uCFb+jXLD+1ymVzC6yUvj/RhOaV26YvLFpdgNDU3+l5sok4etQO14UGgNt7Mxieklmw0RquDf7wzUbs5jA3kUgxkeJPhbVFf0tgupzONAt8N6mGVxSpOYaJuFNH8CMVsT0rUlmP1c7CTa+KVAiLTkjVayWGoxNdeJGJ3FO/BLH3vlR5E/o131L9VTLeQpHywuP7UFkcM+34vaczjSd7ZtVCTzgm0jAt3Mz/LpMYrNpcAqstOYKjYUlfioO4EmsssZrWVCA+7b9JIhvYZO9YYOTN5+eFLxpk+sKIVZwHXGgz+8Ik=
  file:
    - target/ebms-admin-$project_version.jar
  skip_cleanup: true
  on:
    repo: java-ebms-adapter/ebms-admin-console
    branch: master
  name: "$project_version"
addons:
  sonarcloud:
    organization: java-ebms-adapter
    token:
      secure: "UgSGTXsADyb8NsPtZSCwUDIfWeRB80oN/HHkaPdrjPsHf6Q+d5eP6dGpf9GuimWUrFXZ6hPsCB45WfwJOESAtiRgZjlpINGXhsOoaOjeQLOjH1Djs9vcp4hhMQPIz0Yj89KXNNBRyc9m7AfxmDAQ6Oak0cfAHj2kSw093cTeh5lXlXpAqWE/UzQnLN8JxmtJs6bov2TwKkeIAb1f/JPMZJefHBHwEHiA0fYCGqM9DULgZSrA9N6cZFvPQ3D4t8ZQlEDkE5B131XGO1X3KHDzt4525/WOK5ws3oNSwUcrUxJmhA31Ve5HCgLads1Lim+XHT49JsnUnwa7HLPILSsEgOR4PzC4lxVBRWo3VOowjKnhRikUoNM47kigLQusP8iVWvxMh4jAPrx95p6kTQAfTP5Wd9IRNeAa1IMMi580fusF36QszHlHQhR09v0/oMb5Dl/poNqB2PmlUhBEEuAMHejcm4xH8VZOaN2IezWRs4CBziyRp0WMf74xZcG6WQ3XVCnwmDOqz36h+yGbGv2ey6oW4FhwiUefg9auUvobwqMYt15RUmTNk/l/MX5tOj/3JtzS5pLdQQKhbhEG2o4aVSjNuwYm9mM7+C3rd82wg8b9w53KYibDj2jqDFyoOBmccEEqasNzvlRqdwq364TZb6euhMV1mTIbxKOardhvVQo="
script:
  # The following command line builds the project, runs the tests with coverage and then executes the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=java-ebms-adapter_ebms-admin-console
