language: java
jdk: openjdk8
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version | grep -v '\[')
deploy:
  provider: releases
  api_key:
    secure: TaWXrg5y0wS2WBguaI9x8a/Wk0l6wKsAYfcsrUM+uly6Eh60p2n3EH2/n+fZAmKJFpg9t745H2yFJHVKIVuKQY1khPhaxx8apcnsWnP0CQSpFC6zc7ciSgE8mT2whY4EsFX7izHYzcbHF3iuZ3DuKY/wxp+ToYL8oMS7jwZhaxrGl1857J9JW9dFogmGvOsq4aYY0lezSCjxB/ZuHuISXTo2xZww/0iFr1pXWrL0seG9T7jeXv2tJK1V2oQaho7dpSrB8kH6qiBibSH4ieKu9vLugr4UaP3ej7ldPWEozbi63TAR8bf9BHRHcmlcasvyDugGgIi8qkCBg7oVtaCpmafCNgdscttZLED2jt34gsWGwx614vNf4Xgusbb6uCFb+jXLD+1ymVzC6yUvj/RhOaV26YvLFpdgNDU3+l5sok4etQO14UGgNt7Mxieklmw0RquDf7wzUbs5jA3kUgxkeJPhbVFf0tgupzONAt8N6mGVxSpOYaJuFNH8CMVsT0rUlmP1c7CTa+KVAiLTkjVayWGoxNdeJGJ3FO/BLH3vlR5E/o131L9VTLeQpHywuP7UFkcM+34vaczjSd7ZtVCTzgm0jAt3Mz/LpMYrNpcAqstOYKjYUlfioO4EmsssZrWVCA+7b9JIhvYZO9YYOTN5+eFLxpk+sKIVZwHXGgz+8Ik=
  file:
    - target/ebms-admin-$project_version.jar
  skip_cleanup: true
  on:
    repo: java-ebms-adapter/ebms-admin-console
    branch: master
  name: "$project_version"
addons:
  sonarcloud:
    organization: "java-ebms-adapter"
    token:
      secure: "hJHQcSjnk3lWbv2hXqBdEBkEY3tve5kmaf2EcaOunMeJ5STnWs34t/Viy/Gntyn/RNLiTPRplWEZrQ1KhJa+75zIhP3kcVKqrMucfkPjlDYu3xjq2cUiSU1h5dygSM1sueG40eJYMb/+vRqFM+71MVwqgqWZ3V7npLsspCwRhL1WWXe15sMhoFijpyoZ169W4MmugNBNOaWINZgat/tYrvcpFyuUkR8W0An5Kwhv6NxQPDmXFqPUT3K7K3P2r7PdTaf/RWKLToAYKKbI+Jw3ZFlab37W/hpFTCH+lpzs+4atpG5+h5RI8UZC7MIigMokCyGYst2E78ZKjiQKxuHV4xx5gS6uSf4807KFZ+/KGF1hcIGGEBbF/apCk8wkcROWMtqrTE6UJ2fiaFlzUtRXz3POtjrXQGeMlI2yKLjSLhemGYTBX3q0ZaWmrgaO9XMeohqbKswQppKZ2Aznu+rXWP4gWHCw1sY28FD4BHQmFW3RNky+C4KVL7eI/vsS35fcEoCHQdUWHePWHe4qj4OfgPmD4yEFXGOyRPIwUpzBV2DpxVctO9BdYg802+AHm21W93eipUk4upKFViBE106pxxy3onSIRaQo3WbRXqMbJYf4NnlAPhqHkRr3HuZ3pxWc+VNiINu9CBECuxEyjBIJvwJMcFvDJsnkJ1UgDf61m60="
script:
  # The following command line builds the project, runs the tests with coverage and then executes the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=java-ebms-adapter_ebms-admin-console
