language: java
jdk: openjdk8
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version | grep -v '\[')
deploy:
  provider: releases
  api_key:
    secure: TaWXrg5y0wS2WBguaI9x8a/Wk0l6wKsAYfcsrUM+uly6Eh60p2n3EH2/n+fZAmKJFpg9t745H2yFJHVKIVuKQY1khPhaxx8apcnsWnP0CQSpFC6zc7ciSgE8mT2whY4EsFX7izHYzcbHF3iuZ3DuKY/wxp+ToYL8oMS7jwZhaxrGl1857J9JW9dFogmGvOsq4aYY0lezSCjxB/ZuHuISXTo2xZww/0iFr1pXWrL0seG9T7jeXv2tJK1V2oQaho7dpSrB8kH6qiBibSH4ieKu9vLugr4UaP3ej7ldPWEozbi63TAR8bf9BHRHcmlcasvyDugGgIi8qkCBg7oVtaCpmafCNgdscttZLED2jt34gsWGwx614vNf4Xgusbb6uCFb+jXLD+1ymVzC6yUvj/RhOaV26YvLFpdgNDU3+l5sok4etQO14UGgNt7Mxieklmw0RquDf7wzUbs5jA3kUgxkeJPhbVFf0tgupzONAt8N6mGVxSpOYaJuFNH8CMVsT0rUlmP1c7CTa+KVAiLTkjVayWGoxNdeJGJ3FO/BLH3vlR5E/o131L9VTLeQpHywuP7UFkcM+34vaczjSd7ZtVCTzgm0jAt3Mz/LpMYrNpcAqstOYKjYUlfioO4EmsssZrWVCA+7b9JIhvYZO9YYOTN5+eFLxpk+sKIVZwHXGgz+8Ik=
  file:
    - target/ebms-admin-$project_version.jar
  skip_cleanup: true
  on:
    repo: java-ebms-adapter/ebms-admin-console
    branch: master
  name: "$project_version"
addons:
  sonarcloud:
    organization: "java-ebms-adapter"
    token:
      secure: "V5kYRIfvVxZv8Y7vCu0t6YnoVaMscKrz4LZ+gZ5SWn6v0hFMCOwVShHNjrO8IKsrQydQOJfq6uRhoMPHau1tRVd7c0qGlWOy9Qgj16PgH9VNSCjja3Z/08QY56YG4mazbeBfCvi9RSisjIkm2qFK/rErRB0C33J5QMypK0P1pUcCkG9aEM7Dai+yzLqzg/g8+9LvWgEpyrgkVEXma8Ta7Y2ndOpCZa9+pyBoTBlMgO5BMlPPtJlUN/Ab784MSfasWBWBYe6PTsQj0nTJNuze6UK5Q4zfhoWJSMNm5QSxJXWY6IOqx2eKYhiIaAtp4WRJdkJKpxeSDd87akG1sZzLcS1t6f0bBAvO5RN8NE/Qzva/hAmBn1YDYhh3afFWKxKn6sVkXM4/ZK88U9kOHQ06hgFPeP0gkaULF/xn5pSMbIJhOXEC4U+LJ5fUK5Jxuw70RoBPKSG1kwOwPE7blWhxr9AMzUN+8P7i5B7Y5VU5uPcE2Pi6LITScS/7Vp3nRiYzBgwUDdTaqNp8/kHQIJOgxFDAcH/rW78nxNi0yB0/2r4EJUlTS9Wpt8CTTdcFTTQ33C2ctS/b++barnyk9O7Pvh41u25DYNMHGoxvrqNZfGlGvhzvDtQNQiU+1pSM2n8EBRIvU7kcmQA8vtGG5NFGhmNjeTkbcokLvYLxCEIxYSE="
script:
  # The following command line builds the project, runs the tests with coverage and then executes the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=java-ebms-adapter_ebms-admin-console
