language: java
jdk: openjdk8
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version | grep -v '\[')
deploy:
  provider: releases
  api_key:
    secure: TaWXrg5y0wS2WBguaI9x8a/Wk0l6wKsAYfcsrUM+uly6Eh60p2n3EH2/n+fZAmKJFpg9t745H2yFJHVKIVuKQY1khPhaxx8apcnsWnP0CQSpFC6zc7ciSgE8mT2whY4EsFX7izHYzcbHF3iuZ3DuKY/wxp+ToYL8oMS7jwZhaxrGl1857J9JW9dFogmGvOsq4aYY0lezSCjxB/ZuHuISXTo2xZww/0iFr1pXWrL0seG9T7jeXv2tJK1V2oQaho7dpSrB8kH6qiBibSH4ieKu9vLugr4UaP3ej7ldPWEozbi63TAR8bf9BHRHcmlcasvyDugGgIi8qkCBg7oVtaCpmafCNgdscttZLED2jt34gsWGwx614vNf4Xgusbb6uCFb+jXLD+1ymVzC6yUvj/RhOaV26YvLFpdgNDU3+l5sok4etQO14UGgNt7Mxieklmw0RquDf7wzUbs5jA3kUgxkeJPhbVFf0tgupzONAt8N6mGVxSpOYaJuFNH8CMVsT0rUlmP1c7CTa+KVAiLTkjVayWGoxNdeJGJ3FO/BLH3vlR5E/o131L9VTLeQpHywuP7UFkcM+34vaczjSd7ZtVCTzgm0jAt3Mz/LpMYrNpcAqstOYKjYUlfioO4EmsssZrWVCA+7b9JIhvYZO9YYOTN5+eFLxpk+sKIVZwHXGgz+8Ik=
  file:
    - target/ebms-admin-$project_version.jar
  skip_cleanup: true
  on:
    repo: java-ebms-adapter/ebms-admin-console
    branch: master
  name: "$project_version"
addons:
  sonarcloud:
    organization: "java-ebms-adapter"
    token:
      secure: "NVCfhWRNNR+lteUQytbKfurpQBg/GHTpPPk1jw29XtbofclKKcYN/3pyZzwSMdxfBl7zs18QOF0FikYZvOeVszwdddejIRPLWiP0PuyM7mFzZ9SNsPQcosgTMBdR/sWg6Z8tVWgqj/kjCd/De4KwJYbzwZTmpF7jdJYNMQeS0YoEunHVveJSwf11u22AXv1Sapecn+nL8t2tmOAAjxmrY8cqQ9a8AV1VYq2ToyaeyExWmUAKC2bSv6nKgPPWkriOpk7vQTYtLXFEP/L54cagCRoocLUSujOYyh+v3ZiAlW4h4Xm9UgtwWIN1eIKtWSJ9j2vzi5781gM9sKaVscmn5y1IbFzxCGreCjlpgzY8xst/c8DD1j0x5K2KMugoMHWsyrS5vKx64+6BWYW7srvZ80gBr4NYeyw8m2BLebLG8Q00OOxjq7Nb1tVVNK8zbZ6Sh6KFf50ff+x2p/eGc8XoetCJhZfQHPlfUJN5ervA0UH94yF2lZYfRtZ3rzj43kXKpKNLy5iQAZB0A8vmMtOK64CkXXRZbMktWJBU57j8DDr6qZwMaybP4ZkeNxVCqz/7KadPpDTjMnfehyRj0rMmc1TNgq3bA6n1YOTb3c/UT4tWDg7cv18WzcVv3Zgwcqk/BPjrZXBYPWbF7WpJoKae2glS6DhUPtX37/svohwqF9o="
script:
  # The following command line builds the project, runs the tests with coverage and then executes the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=java-ebms-adapter_ebms-admin-console
